In [3]:
import numpy as np


In [11]:
arr = np.array([1,2,4,8,9,10])
arr1 = np.array([5,73,5,7,8,9])
print("displaying both array")
print(arr,arr1)
print("greater than comparison")
print(np.greater(arr,arr1))
print("greater or equal to comparison")
print(np.greater_equal(arr,arr1))
print("less than comparison")
print(np.less(arr,arr1))
print("less than or equal to comparison")
print(np.less_equal(arr,arr1))

displaying both array
[ 1  2  4  8  9 10] [ 5 73  5  7  8  9]
greater than comparison
[False False False  True  True  True]
greater or equal to comparison
[False False False  True  True  True]
less than comparison
[ True  True  True False False False]
less than or equal to comparison
[ True  True  True False False False]


In [13]:
even = np.arange(30,71,2)
print(even)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
ide_mat = np.identity(3)
print("Identity matrix of order 3")
print(ide_mat)

Identity matrix of order 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
vec = np.arange(21)
print("vector from 0 to 20")
print(vec)
vec[(vec > 9) & (vec < 16)] *= -1
print("After changing magnitude from 9 to 15")
print(vec)

vector from 0 to 20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After changing magnitude from 9 to 15
[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [24]:
ze_mat = np.diag([1,2,3,4,5])
print("5 * 5 zero matrix with different diagonal")
print(ze_mat)

5 * 5 zero matrix with different diagonal
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [25]:
x = np.array([[0,1,6,7,11],[2,3,56,77,9]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[ 0  1  6  7 11]
 [ 2  3 56 77  9]]
Sum of all elements:
172
Sum of each column:
[ 2  4 62 84 20]
Sum of each row:
[ 25 147]


In [26]:
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [33]:

x = np.array([[0,1,6,7,11],[2,3,56,77,9]])
print("First array:")
print(x)
y = np.array([[0,1,6,7,11],[2,3,56,77,9]])
print("Second array:")
print(y)
print("Test above two arrays are")
array_equal = np.allclose(x, y)
if array_equal == True:
    print("Both are equal")
else:
    print("Both are not equal")
    


First array:
[[ 0  1  6  7 11]
 [ 2  3 56 77  9]]
Second array:
[[ 0  1  6  7 11]
 [ 2  3 56 77  9]]
Test above two arrays are
Both are equal


In [34]:

nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [35]:
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
